Document: php5-pdouser
Title: Debian php5-pdouser Manual
Author: <insert document author here>
Abstract: This manual describes what php5-pdouser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/php5-pdouser/php5-pdouser.sgml.gz

Format: postscript
Files: /usr/share/doc/php5-pdouser/php5-pdouser.ps.gz

Format: text
Files: /usr/share/doc/php5-pdouser/php5-pdouser.text.gz

Format: HTML
Index: /usr/share/doc/php5-pdouser/html/index.html
Files: /usr/share/doc/php5-pdouser/html/*.html
